#!/bin/bash

echo "🧪 TestSprite MCP Test Configuration"
echo "===================================="
echo ""
echo "Your TestSprite MCP is configured with:"
echo "  ✅ API Key: Set in ~/.cursor/mcp.json"
echo "  ✅ Project Config: testsprite-mcp-config.json"
echo ""
echo "Application Status:"
curl -s http://localhost:8081 > /dev/null && echo "  ✅ Backend: Running" || echo "  ❌ Backend: Not running"
curl -s http://localhost:3000 > /dev/null && echo "  ✅ Frontend: Running" || echo "  ❌ Frontend: Not running"
echo ""
echo "Test Users:"
echo "  ✅ Admin: admin@test.com / admin123"
echo "  ✅ User: user@test.com / user123"
echo "  ✅ Supplier: supplier@test.com / supplier123"
echo "  ✅ Pharmacy: pharmacy@test.com / pharmacy123"
echo ""
echo "📋 Next Steps:"
echo "1. Use TestSprite MCP tools in Cursor to:"
echo "   - Create test project"
echo "   - Configure authentication"
echo "   - Generate/import test plan"
echo "   - Execute tests"
echo ""
echo "2. Or use TestSprite Web Portal:"
echo "   - Visit https://www.testsprite.com/"
echo "   - Import testsprite-test-plan.json"
echo ""
echo "📁 Configuration Files:"
echo "  - testsprite-mcp-config.json (MCP config)"
echo "  - testsprite-test-plan.json (Test plan)"
echo "  - TESTSPRITE_MCP_USAGE.md (Usage guide)"
echo ""
